import terms from './terms-es.json';
import countryNames from './countries-es.json';
/** Translations for data-generated content and previously saved bilingual games.
 * Names, templates and units are translated; IDs, values and source credits are untouched. */
const capitals: Record<string,string> = {
'London':'Londres','Paris':'París','Rome':'Roma','Vienna':'Viena','Brussels':'Bruselas','Athens':'Atenas','Berlin':'Berlín','Warsaw':'Varsovia','Lisbon':'Lisboa','Copenhagen':'Copenhague','Stockholm':'Estocolmo','Bucharest':'Bucarest','Prague':'Praga','Moscow':'Moscú','Kyiv':'Kiev','Belgrade':'Belgrado','Bern':'Berna','Amsterdam':'Ámsterdam','Budapest':'Budapest','Reykjavik':'Reikiavik','Dublin':'Dublín','Luxembourg':'Luxemburgo','Mexico City':'Ciudad de México','Havana':'La Habana','Panama City':'Ciudad de Panamá','Guatemala City':'Ciudad de Guatemala','Port-au-Prince':'Puerto Príncipe','Port of Spain':'Puerto España','Washington, D.C.':'Washington D. C.','Brasília':'Brasilia','Lima':'Lima','Quito':'Quito','Asunción':'Asunción','Tokyo':'Tokio','Beijing':'Pekín','Seoul':'Seúl','Pyongyang':'Pionyang','New Delhi':'Nueva Delhi','Jerusalem':'Jerusalén','Baghdad':'Bagdad','Tehran':'Teherán','Riyadh':'Riad','Beirut':'Beirut','Damascus':'Damasco','Kuwait City':'Ciudad de Kuwait','Abu Dhabi':'Abu Dabi','Muscat':'Mascate','Amman':'Amán','Kathmandu':'Katmandú','Dhaka':'Daca','Hanoi':'Hanói','Manila':'Manila','Jakarta':'Yakarta','Singapore':'Singapur','Dili':'Dili','Bishkek':'Biskek','Dushanbe':'Dusambé','Tashkent':'Taskent','Ashgabat':'Asjabad','Ulan Bator':'Ulán Bator','Ulaanbaatar':'Ulán Bator','Yerevan':'Ereván','Tbilisi':'Tiflis','Baku':'Bakú','Nicosia':'Nicosia','Cairo':'El Cairo','Algiers':'Argel','Tunis':'Túnez','Tripoli':'Trípoli','Khartoum':'Jartum','Addis Ababa':'Adís Abeba','Djibouti':'Yibuti','Mogadishu':'Mogadiscio','Cape Town':'Ciudad del Cabo','Accra':'Acra','Yaoundé':'Yaundé','Bangui':'Bangui','N’Djamena':'Yamena',"N'Djamena":'Yamena','Nouakchott':'Nuakchot','Ouagadougou':'Uagadugú','Bissau':'Bisáu','Port Louis':'Port Louis','Moroni':'Moroni','Porto-Novo':'Porto Novo','São Tomé':'Santo Tomé','Victoria':'Victoria','Antananarivo':'Antananarivo','Maputo':'Maputo','Canberra':'Canberra','Wellington':'Wellington','Port Moresby':'Puerto Moresby','Vatican City':'Ciudad del Vaticano','San Marino':'San Marino','Monaco':'Mónaco','Andorra la Vella':'Andorra la Vieja','Saint John’s':'Saint John’s','St. George’s':'Saint George’s','Sofia':'Sofía','Tallinn':'Tallin','Vilnius':'Vilna','Chișinău':'Chisináu','Ljubljana':'Liubliana','Skopje':'Skopie','Sanaa':'Saná','Malé':'Malé','Naypyidaw':'Naipyidó','Nay Pyi Taw':'Naipyidó','Phnom Penh':'Nom Pen','Vientiane':'Vientián','Sri Jayawardenepura Kotte':'Sri Jayawardenepura Kotte'
};
export const spanishCountry = (name:string) => (countryNames as Record<string,string>)[name] ?? name;
export const spanishCapital = (name:string) => capitals[name] ?? name;
const words:Record<string,string> = {
...terms,...countryNames,...capitals,
World:'Mundo',Europe:'Europa',Africa:'África',Asia:'Asia','North America':'América del Norte','South America':'América del Sur',Oceania:'Oceanía','Western Europe':'Europa occidental','Northern Europe':'Europa septentrional','Southern Europe':'Europa meridional','Eastern Europe':'Europa oriental','Central Europe':'Europa central','Western Asia':'Asia occidental','Eastern Asia':'Asia oriental','Southern Asia':'Asia meridional','South-Eastern Asia':'Sudeste asiático','Southeast Asia':'Sudeste asiático','Central Asia':'Asia central','Northern Africa':'África septentrional','Western Africa':'África occidental','Middle Africa':'África central','Eastern Africa':'África oriental','Southern Africa':'África meridional','Central America':'América Central','Caribbean':'Caribe','Northern America':'América del Norte','Australia and New Zealand':'Australia y Nueva Zelanda',Melanesia:'Melanesia',Micronesia:'Micronesia',Polynesia:'Polinesia',
'Population':'Población','Forest cover':'Cobertura forestal','Country size':'Superficie del país','Life expectancy':'Esperanza de vida','City living':'Población urbana','GDP per person':'PIB por habitante','Land neighbours':'Vecinos terrestres','Internet use':'Uso de internet','Births per woman':'Hijos por mujer','Agricultural land':'Tierras agrícolas','Total economy':'Economía total','From the equator':'Distancia al ecuador','Exports':'Exportaciones','Further north':'Más al norte','Highest point':'Punto más alto','Highest peak':'Cumbre más alta','Mean elevation':'Altitud media','Average elevation':'Altitud media','Coastline':'Longitud de costa','Median age':'Edad mediana','Total area':'Superficie total','Total GDP':'PIB total',
'Which country has more people?':'¿Qué país tiene más habitantes?','Which country has a larger share of forest?':'¿Qué país tiene un mayor porcentaje de bosque?','Which country covers more area?':'¿Qué país tiene mayor superficie?','Where is life expectancy at birth higher?':'¿Dónde es mayor la esperanza de vida al nacer?','Where does a larger share of people live in cities?':'¿Dónde vive un mayor porcentaje de la población en ciudades?','Which country has a higher GDP per person?':'¿Qué país tiene un PIB por habitante más alto?','Which country has more land neighbours?':'¿Qué país tiene más vecinos terrestres?','Where does a larger share of people use the internet?':'¿Dónde usa internet un mayor porcentaje de la población?','Where is the fertility rate higher?':'¿Dónde es mayor la tasa de fecundidad?','Which country has a larger share of agricultural land?':'¿Qué país tiene un mayor porcentaje de tierras agrícolas?','Which country has a larger total GDP?':'¿Qué país tiene un PIB total más alto?','Which country’s reference point is farther from the equator?':'¿Qué país tiene su punto de referencia más lejos del ecuador?','Where are exports a larger share of GDP?':'¿Dónde representan las exportaciones un mayor porcentaje del PIB?','Which country’s reference point is farther north?':'¿Qué país tiene su punto de referencia más al norte?',
'Total resident population, including all ages.':'Población residente total, de todas las edades.','Forest as a percentage of land area, not the total size of its forests.':'Bosque como porcentaje de la superficie terrestre, no su superficie total.','Total area from the country catalog. Territorial conventions follow the source.':'Superficie total del catálogo de países. La delimitación territorial sigue la fuente.','Expected years of life at birth, based on mortality rates in the reference year.':'Años de vida esperados al nacer, según las tasas de mortalidad del año de referencia.','Urban population as a share of the total. Urban definitions vary by country.':'Población urbana como porcentaje del total. La definición de zona urbana varía entre países.','GDP divided by population, in current US dollars. This is not a measure of personal salary.':'PIB dividido entre la población, en dólares estadounidenses corrientes. No mide el salario personal.','Land neighbours in the source catalog. Sea boundaries do not count.':'Vecinos terrestres del catálogo. Las fronteras marítimas no cuentan.','People who used the internet in the last three months, as a share of the population.':'Porcentaje de la población que usó internet en los últimos tres meses.','Expected births per woman if the reference year’s age-specific fertility rates remained constant.':'Número esperado de hijos por mujer si se mantuvieran las tasas de fecundidad por edad del año de referencia.','Arable land, permanent crops and permanent pasture as a percentage of land area.':'Tierras de cultivo, cultivos permanentes y pastos permanentes como porcentaje de la superficie terrestre.','Annual gross domestic product in current US dollars; exchange rates affect comparisons.':'Producto interior bruto anual en dólares estadounidenses corrientes; los tipos de cambio afectan a la comparación.','Distance from the equator to the catalog’s representative point, not the closest border.':'Distancia del ecuador al punto representativo del catálogo, no a la frontera más cercana.','Exports of goods and services relative to GDP. This can exceed 100% in trading economies.':'Exportaciones de bienes y servicios respecto al PIB. Pueden superar el 100 % en economías comerciales.','Latitude of the catalog’s representative point, not the northernmost border.':'Latitud del punto representativo del catálogo, no de la frontera más septentrional.',
'Elevation above sea level. The source’s territorial convention applies; the summit name is revealed after matching.':'Altitud sobre el nivel del mar. Se aplica la delimitación territorial de la fuente; el nombre de la cumbre se revela al conectar el país.','Average terrain elevation above sea level, rather than the height of the highest mountain.':'Altitud media del terreno sobre el nivel del mar, no la altura de la montaña más alta.','Coastline length in the archived Factbook. Length depends on the measuring method and which islands the source includes.':'Longitud de costa del archivo Factbook. Depende del método de medición y de las islas incluidas en la fuente.','Half of the population is younger than this age and half is older. This is neither the average age nor life expectancy.':'La mitad de la población es más joven que esta edad y la otra mitad mayor. No es la edad media ni la esperanza de vida.','Total country area from the country catalogue, following its territorial convention.':'Superficie total del país en el catálogo, según su delimitación territorial.','Elevation of the highest point above sea level. Shared summits can have equal ranks.':'Altitud del punto más alto sobre el nivel del mar. Las cumbres compartidas pueden empatar.','Mean elevation of the country’s land above sea level.':'Altitud media del terreno del país sobre el nivel del mar.','Coastline length in the archived source. Measurements depend on scale and method.':'Longitud de costa de la fuente archivada. Las mediciones dependen de la escala y del método.','Half the population is younger than this age, half older. A 2025 estimate, not an arithmetic average.':'La mitad de la población es más joven y la otra mitad mayor. Estimación de 2025, no una media aritmética.',
'm above sea level':'m sobre el nivel del mar','km of coastline':'km de costa',years:'años',people:'habitantes','per woman':'por mujer','US dollars':'dólares estadounidenses','Archived source':'Fuente archivada','Source catalogue':'Catálogo de origen',
'Which country flies this flag?':'¿A qué país pertenece esta bandera?','Follow the trail. Which country am I?':'Sigue las pistas. ¿Qué país soy?','My flag looks like this.':'Mi bandera es así.','I have no land borders with other countries in this atlas.':'No tengo fronteras terrestres con otros países de este atlas.','Put these countries in order. Largest area first.':'Ordena estos países. El de mayor superficie primero.','A pin inside the country or within 25 km of its mapped boundary is accepted. Included islands count too.':'Se acepta un marcador dentro del país o a menos de 25 km de su frontera dibujada. Las islas incluidas también cuentan.',
'First footprint':'Primera huella','Finding your feet':'Abriendo camino','Regular rover':'Viajero habitual','Frequent flyer':'Viajero frecuente','Around again':'Otra vuelta','Good instincts':'Buena intuición','World minded':'Mente viajera','Walking atlas':'Atlas andante','Lift off':'Despegue','Above the clouds':'Sobre las nubes','Out of this world':'Fuera de este mundo','Legend of the latitude':'Leyenda del mapa','On a roll':'En racha','Ten out of ten':'Diez de diez','Unbroken':'Imparable','Today is the day':'Hoy es el día','A week of wonders':'Una semana de maravillas','A world of habit':'Un hábito mundial','Room champion':'Campeón de la sala','Friendly rivalry':'Rivalidad amistosa','The one to beat':'El rival a batir','Better together':'Mejor en compañía','The usual crew':'El grupo de siempre','Clean sweep':'Sin fallos','Precision pilot':'Piloto de precisión','Flying colours':'Banderas al viento','City connections':'Conexiones urbanas','On the spot':'En el punto exacto','Good neighbours':'Buenos vecinos','In good order':'Todo en orden'
};
export function spanishContent(en:string):string {
  if (words[en] !== undefined) return words[en];
  let m:RegExpMatchArray|null;
  if ((m=en.match(/^(What is the capital|Which is a capital) of (.+)\?$/))) return `${m[1].startsWith('Which')?'¿Cuál es una de las capitales':'¿Cuál es la capital'} de ${spanishCountry(m[2])}?`;
  if ((m=en.match(/^Drop a pin in (.+)\.$/))) return `Coloca un marcador en ${spanishCountry(m[1])}.`;
  if ((m=en.match(/^Which country shares a land border with (.+)\?$/))) return `¿Qué país comparte frontera terrestre con ${spanishCountry(m[1])}?`;
  if ((m=en.match(/^Start your search in (.+)\.$/))) return `Empieza tu búsqueda en ${spanishContent(m[1])}.`;
  if ((m=en.match(/^I share a land border with (.+)\.$/))) return `Comparto una frontera terrestre con ${spanishCountry(m[1])}.`;
  if ((m=en.match(/^My total area is approximately (.+) km²\.$/))) return `Mi superficie total es de unos ${Number(m[1].replace(/,/g,'')).toLocaleString('es')} km².`;
  if ((m=en.match(/^(.+) and (.+) share a land border\.$/))) return `${spanishCountry(m[1])} y ${spanishCountry(m[2])} comparten frontera terrestre.`;
  if ((m=en.match(/^(.+) is in (.+)\. (?:Its capital (?:cities are|is) (.+)\.)?$/))) return `${spanishCountry(m[1])} está en ${spanishContent(m[2])}.${m[3]?' Capital: '+m[3].split(' / ').map(spanishCapital).join(' / ')+'.':''}`;
  if ((m=en.match(/^The target is a representative point in (.+)\. Distance is measured to this point\.$/))) return `El destino es un punto representativo de ${spanishCountry(m[1])}. La distancia se mide hasta ese punto.`;
  if (en.includes(' → ')) return en.split(' → ').map(spanishContent).join(' → ');
  if (en.includes(' / ')) return en.split(' / ').map(spanishContent).join(' / ');
  if (en.includes(' · ')) return en.split(' · ').map(spanishContent).join(' · ');
  if ((m=en.match(/^(.+?): (.+)$/))) return spanishContent(m[1])+': '+spanishContent(m[2]);
  if ((m=en.match(/^([\d,.]+) km²$/))) return Number(m[1].replace(/,/g,'')).toLocaleString('es')+' km²';
  // Numeric fact fragments: only translate recognised labels/units, never identifiers.
  for(const [original,translated] of Object.entries(words)) if(original.length>15 && en.endsWith(original)) return spanishContent(en.slice(0,-original.length))+translated;
  return en.replace(/(\d[\d,.]*) (m above sea level|km of coastline|US dollars|people|years|per woman)/g,(_,n,u)=>n+' '+words[u]).replace(/(\d{4}) estimate/g,'$1 · estimación');
}
export function localized(en:string,nl:string,es=spanishContent(en)) { return {en,nl,es}; }
/** Also upgrades old saved sessions without altering their questions or results. */
export function withSpanish<T>(value:T):T {
  if(Array.isArray(value))return value.map(withSpanish) as T;
  if(!value || typeof value!=='object')return value;
  const source=value as Record<string,unknown>;
  const out=Object.fromEntries(Object.entries(source).map(([k,v])=>[k,withSpanish(v)]));
  if(typeof source.en==='string'&&typeof source.nl==='string'&&!source.es)out.es=spanishContent(source.en);
  if(typeof source.name==='string'&&typeof source.nl==='string'&&!source.es)out.es=spanishCountry(source.name);
  return out as T;
}
