export const rankMessages = {
  en: {
    rank:'Rank Radar', rankCardCopy:'Every country has a surprising side. Can you spot it?', cardVerbrank:'Discover', rankExtent:'6 countries', rankKinds:'Peaks, people, coastlines & more', rankPractice:'Another round of Rank Radar',
    rankQuestion:'Where does {country} rank highest?', rankIntro:'Pick its strongest relative position out of these four subjects.', rankRules:'How the radar works', rankRulesCopy:'Higher values rank first. We compare relative positions among the countries with data for each subject. Smaller “top %” means nearer the top. Ties share a rank; close calls are left out. A rank compares numbers, not the worth of a country.',
    rankRight:'You found its surprising side!', rankWrong:'A different subject comes out on top.', rankBecause:'{winner} ranks #{rank} of {count} countries (top {percent}%).', rankInstead:'Your choice, {choice}, ranks #{rank} of {count} (top {percent}%).', rankBest:'Highest position', rankYourChoice:'Your choice', rankOther:'Also worth discovering', rankChoose:'Choose this subject', rankOf:'of {n} countries', rankTop:'Top {n}%', rankData:'About this number', rankArchived:'Archived geography · year not specified', rankEstimate:'estimate', rankFinish:'Six countries. Six new perspectives.', rankFinishCopy:'Keep one surprising fact with you. That is a good day’s exploring.', rankReview:'Your discoveries', rankMore:'Explore six more', rankSourceNote:'Ranks use our 195-country collection where data are available. Each subject keeps its own source year.', rankTopics:'15 subjects. Something unexpected every day.', rankDay:'Today’s radar', rankSaved:'Your choices are saved as you go.', rankLoading:'Finding your next discovery…', rankValue:'Value', rankFresh:'A fresh perspective, every day.'
  },
  nl: {
    rank:'Rank Radar', rankCardCopy:'Elk land heeft een verrassende kant. Zie jij welke?', cardVerbrank:'Ontdek', rankExtent:'6 landen', rankKinds:'Bergen, bevolking, kustlijnen & meer', rankPractice:'Nog een ronde Rank Radar',
    rankQuestion:'Waarin staat {country} het hoogst?', rankIntro:'Kies de sterkste relatieve positie uit deze vier onderwerpen.', rankRules:'Zo werkt de radar', rankRulesCopy:'Hogere waarden staan bovenaan. We vergelijken de relatieve positie tussen de landen met gegevens per onderwerp. Een lager “top %” betekent dichter bij de top. Gelijke waarden delen een positie; twijfelgevallen laten we weg. Een rang vergelijkt cijfers, niet de waarde van een land.',
    rankRight:'Je hebt de verrassende kant gevonden!', rankWrong:'Een ander onderwerp staat hoger.', rankBecause:'{winner} staat op #{rank} van {count} landen (top {percent}%).', rankInstead:'Jouw keuze, {choice}, staat op #{rank} van {count} (top {percent}%).', rankBest:'Hoogste positie', rankYourChoice:'Jouw keuze', rankOther:'Ook leuk om te weten', rankChoose:'Kies dit onderwerp', rankOf:'van {n} landen', rankTop:'Top {n}%', rankData:'Over dit cijfer', rankArchived:'Geografisch archief · jaar niet vermeld', rankEstimate:'schatting', rankFinish:'Zes landen. Zes nieuwe inzichten.', rankFinishCopy:'Neem één verrassend feitje mee. Dan is je ontdekkingstocht al geslaagd.', rankReview:'Jouw ontdekkingen', rankMore:'Ontdek nog zes landen', rankSourceNote:'De rangposities gebruiken onze collectie van 195 landen waarvoor gegevens beschikbaar zijn. Elk onderwerp behoudt zijn eigen bronjaar.', rankTopics:'15 onderwerpen. Elke dag iets onverwachts.', rankDay:'De radar van vandaag', rankSaved:'Je keuzes worden tussendoor opgeslagen.', rankLoading:'Op zoek naar je volgende ontdekking…', rankValue:'Waarde', rankFresh:'Elke dag een frisse blik.'
  }
};
