"""Project-authored EN/NL adaptations of the cited licensed UNESCO descriptions.
Run from the repository root. This is a deterministic local export, not a scraper.
"""
import json
from pathlib import Path

# country, property ID, title, theme, first clue EN/NL, alternate EN/NL, explanation EN/NL
rows = [
('ECU',1,'Galápagos Islands','wildlife',
 'Finches and giant tortoises on its volcanic islands helped inspire Darwin.',
 'Vinken en reuzenschildpadden op vulkanische eilanden inspireerden Darwin.',
 'Three ocean currents meet around its Galápagos Islands.',
 'Rond de Galápagoseilanden komen drie zeestromen samen.',
 'The Galápagos lie in the Pacific, where three ocean currents meet. Their isolation allowed unusual species to evolve; Darwin visited in 1835.',
 'De Galápagos liggen in de Stille Oceaan, waar drie zeestromen samenkomen. Door hun isolement ontstonden bijzondere soorten. Darwin bezocht de eilanden in 1835.'),
('EGY',1186,'Wadi Al-Hitan (Whale Valley)','fossils',
 'Whale fossils with traces of hind legs lie in its Wadi Al-Hitan desert.',
 'In de woestijn van Wadi Al-Hitan liggen walvisfossielen met resten van achterpoten.',
 'Its Whale Valley records how whales evolved from land animals into ocean dwellers.',
 'De Walvisvallei laat zien hoe walvissen van landdieren in zeebewoners veranderden.',
 'Wadi Al-Hitan preserves early whales from a time when this desert lay beneath the sea. Their skeletons document the transition from life on land to life in the ocean.',
 'Wadi Al-Hitan bewaart vroege walvissen uit een tijd waarin deze woestijn onder zee lag. Hun skeletten tonen de overgang van een leven op het land naar een leven in zee.'),
('BWA',1432,'Okavango Delta','water',
 'The Okavango spreads into an inland delta instead of reaching the sea.',
 'De Okavango stroomt uit in een binnendelta in plaats van de zee.',
 'Its Okavango wetlands receive their annual flood during the dry season.',
 'De Okavangomoerassen krijgen hun jaarlijkse overstroming juist in het droge seizoen.',
 'The Okavango is an inland delta without an outlet to the sea. Its seasonal floods arrive during the local dry season, sustaining wildlife in an otherwise arid landscape.',
 'De Okavango is een binnendelta zonder afvoer naar zee. De jaarlijkse overstroming komt in het plaatselijke droge seizoen en ondersteunt dieren in een verder droog landschap.'),
('NAM',1430,'Namib Sand Sea','landscapes',
 'Fog is the main water source for life among its Namib coastal dunes.',
 'Mist is de belangrijkste waterbron voor leven tussen de kustduinen van de Namib.',
 'The dunes of its Namib Sand Sea meet a foggy Atlantic coast.',
 'De duinen van de Namibzandzee grenzen aan een mistige Atlantische kust.',
 'The Namib Sand Sea combines vast dune fields with coastal fog. Animals and plants here depend on moisture carried in from the ocean.',
 'De Namibzandzee combineert uitgestrekte duinen met kustmist. Dieren en planten zijn er afhankelijk van vocht dat vanaf de oceaan binnenkomt.'),
('MDG',494,'Andrefana Dry Forests','landscapes',
 'Its Bemaraha landscape is a maze of sharp limestone needles called tsingy.',
 'Het landschap van Bemaraha is een doolhof van scherpe kalksteennaalden: tsingy.',
 'Lemurs live among forests and limestone pinnacles in its Bemaraha region.',
 'In de regio Bemaraha leven lemuren tussen bossen en kalksteenpieken.',
 'Bemaraha is part of the Andrefana Dry Forests World Heritage property. Its spectacular limestone formations, known as tsingy, shelter distinctive island wildlife.',
 'Bemaraha hoort bij het werelderfgoed Andrefana Dry Forests. De spectaculaire kalksteenformaties, tsingy genoemd, bieden onderdak aan bijzondere eilanddieren.'),
('AUS',1094,'Purnululu National Park','landscapes',
 'Its Bungle Bungle Range has striped sandstone towers shaped like beehives.',
 'De Bungle Bungle Range heeft gestreepte zandsteentorens in de vorm van bijenkorven.',
 'Cyanobacteria create dark bands on its Purnululu sandstone domes.',
 'Cyanobacteriën vormen donkere banden op de zandsteenkoepels van Purnululu.',
 'Erosion shaped the beehive-like towers of Purnululu. The darker bands hold more moisture, allowing cyanobacteria to grow on the sandstone.',
 'Erosie vormde de bijenkorfachtige torens van Purnululu. De donkere banden houden meer vocht vast, waardoor cyanobacteriën op het zandsteen kunnen groeien.'),
('MYS',1013,'Gunung Mulu National Park','caves',
 'Vast caves in Gunung Mulu shelter millions of bats and swiftlets.',
 'Enorme grotten in Gunung Mulu bieden onderdak aan miljoenen vleermuizen en gierzwaluwen.',
 'Its Sarawak Chamber is an underground space roughly 600 metres long.',
 'De ondergrondse Sarawakkamer is ongeveer 600 meter lang.',
 'Gunung Mulu lies in Sarawak on Borneo. Its limestone cave systems include Sarawak Chamber, a vast natural room about 600 metres long and 415 metres wide.',
 'Gunung Mulu ligt in Sarawak op Borneo. Het kalkstenen grottenstelsel bevat de Sarawakkamer: een natuurlijke ruimte van ongeveer 600 meter lang en 415 meter breed.'),
('ISL',1267,'Surtsey','science',
 'Its island Surtsey rose from the sea during a volcanic eruption beginning in 1963.',
 'Het eiland Surtsey rees uit zee tijdens een vulkaanuitbarsting die in 1963 begon.',
 'Scientists study how life colonises its protected volcanic island of Surtsey.',
 'Wetenschappers volgen hoe leven zich vestigt op het beschermde vulkaaneiland Surtsey.',
 'Surtsey formed during eruptions from 1963 to 1967. Strict protection makes it a natural laboratory for studying how plants and animals arrive on new land.',
 'Surtsey ontstond door uitbarstingen tussen 1963 en 1967. Strenge bescherming maakt het een natuurlijk laboratorium voor de komst van planten en dieren op nieuw land.'),
('GBR',369,"Giant’s Causeway and Causeway Coast",'landscapes',
 'Around 40,000 basalt columns form its Giant’s Causeway.',
 'Ongeveer 40.000 basaltzuilen vormen er de Giant’s Causeway.',
 'Ancient volcanic activity built its geometric Giant’s Causeway coastline.',
 'Vulkanische activiteit vormde de geometrische kustlijn van de Giant’s Causeway.',
 'The Giant’s Causeway is in County Antrim, Northern Ireland, part of the United Kingdom. Cooling volcanic rock produced its striking columns.',
 'De Giant’s Causeway ligt in County Antrim in Noord-Ierland, onderdeel van het Verenigd Koninkrijk. De opvallende zuilen ontstonden toen vulkanisch gesteente afkoelde.'),
('TUR',485,'Hierapolis-Pamukkale','water',
 'Mineral-rich hot springs built the white terraces of Pamukkale.',
 'Mineraalrijke warmwaterbronnen bouwden de witte terrassen van Pamukkale.',
 'The ancient spa city of Hierapolis overlooks white mineral pools here.',
 'De oude kuurstad Hierapolis kijkt hier uit over witte mineraalbassins.',
 'Water from hot springs deposits calcite at Pamukkale, gradually forming white basins and terraces. The ancient spa settlement of Hierapolis stands nearby.',
 'Warmwaterbronnen zetten bij Pamukkale calciet af. Zo groeien witte bassins en terrassen. De oude kuurstad Hierapolis ligt er vlakbij.'),
('GRC',455,'Meteora','heritage',
 'Monasteries at Meteora stand on top of towering rock pillars.',
 'De kloosters van Meteora staan boven op torenhoge rotspilaren.',
 'Monks settled among its Meteora sandstone peaks from the 11th century.',
 'Vanaf de 11e eeuw vestigden monniken zich tussen de zandsteenpieken van Meteora.',
 'Meteora combines dramatic sandstone pillars with monasteries perched above the plain. The difficult terrain offered monks places of seclusion.',
 'Meteora combineert indrukwekkende zandsteenpilaren met kloosters hoog boven de vlakte. Het moeilijk bereikbare terrein bood monniken afzondering.'),
('HRV',98,'Plitvice Lakes National Park','water',
 'Mineral deposits keep building natural dams between its Plitvice lakes.',
 'Mineralen bouwen voortdurend natuurlijke dammen tussen de Plitvicemeren.',
 'Waterfalls link the terraced lakes of Plitvice in its limestone landscape.',
 'Watervallen verbinden de getrapte Plitvicemeren in een kalksteenlandschap.',
 'At Plitvice, flowing water deposits calcium carbonate. These travertine barriers create lakes and waterfalls, and the process continues today.',
 'Bij Plitvice zet stromend water calciumcarbonaat af. Deze travertijnbarrières vormen meren en watervallen. Dat proces gaat nog steeds door.'),
('POL',32,'Wieliczka and Bochnia Royal Salt Mines','heritage',
 'Underground chapels and statues were carved from salt at Wieliczka.',
 'Bij Wieliczka zijn ondergrondse kapellen en beelden uit zout gehouwen.',
 'Rock-salt mining at Wieliczka and Bochnia began in the 13th century.',
 'In de mijnen van Wieliczka en Bochnia werd vanaf de 13e eeuw steenzout gewonnen.',
 'The Wieliczka and Bochnia salt mines preserve centuries of mining history. Their underground spaces include chapels, sculptures and equipment illustrating the trade.',
 'De zoutmijnen Wieliczka en Bochnia bewaren eeuwen mijnbouwgeschiedenis. Ondergronds zijn kapellen, beelden en werktuigen te vinden die het ambacht laten zien.'),
('JOR',326,'Petra','heritage',
 'Nabataean builders carved much of Petra directly into the rock.',
 'Nabatese bouwers hakten grote delen van Petra rechtstreeks uit de rotsen.',
 'Its rock-cut city of Petra stood on caravan routes between the Red and Dead Seas.',
 'De rotsstad Petra lag aan karavaanroutes tussen de Rode Zee en de Dode Zee.',
 'Petra was a Nabataean caravan centre. Buildings cut into the cliffs combine with an engineered water system in a landscape of mountains and gorges.',
 'Petra was een Nabatese karavaanstad. Uit rotsen gehouwen gebouwen en een aangelegd watersysteem liggen in een landschap van bergen en kloven.'),
('LKA',202,'Ancient City of Sigiriya','heritage',
 'Ruins of a royal capital crown its 180-metre-high Lion Rock at Sigiriya.',
 'Op de 180 meter hoge Leeuwenrots van Sigiriya liggen de ruïnes van een koninklijke hoofdstad.',
 'The ascent to Sigiriya once passed through a huge lion-shaped gateway.',
 'De klim naar Sigiriya liep ooit door een enorme poort in de vorm van een leeuw.',
 'Sigiriya was a royal capital in the fifth century. Its palace ruins occupy the summit of a steep rock, approached by a stairway through a monumental lion entrance.',
 'Sigiriya was in de vijfde eeuw een koninklijke hoofdstad. De paleisruïnes liggen op een steile rots, bereikbaar via een trap door een monumentale leeuwenpoort.'),
('IDN',592,'Borobudur Temple Compounds','heritage',
 'Seventy-two openwork stupas surround the central dome of Borobudur.',
 'Rond de centrale koepel van Borobudur staan 72 opengewerkte stoepa’s.',
 'Its Buddhist temple of Borobudur was built on Java in the eighth and ninth centuries.',
 'De boeddhistische tempel Borobudur werd in de achtste en negende eeuw op Java gebouwd.',
 'Borobudur is a terraced Buddhist monument on Java. The upper circular platforms carry 72 perforated stupas, each enclosing a statue of the Buddha.',
 'Borobudur is een boeddhistisch monument met terrassen op Java. De bovenste ronde platforms dragen 72 opengewerkte stoepa’s, elk met een Boeddhabeeld.'),
('KHM',668,'Angkor','heritage',
 'Forests surround the former capitals of the Khmer Empire at Angkor.',
 'Bossen omringen bij Angkor de vroegere hoofdsteden van het Khmer-rijk.',
 'Its Angkor complex includes both Angkor Wat and the Bayon temple.',
 'Het complex van Angkor omvat zowel Angkor Wat als de Bayontempel.',
 'Angkor preserves remains of successive Khmer capitals from the ninth to the fifteenth centuries. Its temples sit within a much larger archaeological landscape.',
 'Angkor bewaart resten van opeenvolgende Khmer-hoofdsteden uit de negende tot de vijftiende eeuw. De tempels liggen in een veel groter archeologisch landschap.'),
('VNM',672,'Ha Long Bay – Cat Ba Archipelago','landscapes',
 'Limestone towers rise from the sea in its Ha Long Bay.',
 'In de Ha Longbaai rijzen kalksteentorens op uit zee.',
 'Its Ha Long–Cat Ba seascape contains forested limestone islands and caves.',
 'Het zeegebied Ha Long–Cat Ba bevat beboste kalksteeneilanden en grotten.',
 'Ha Long Bay and the Cat Ba Archipelago form a marine karst landscape. Erosion has shaped the limestone into steep islands, caves and enclosed waters.',
 'De Ha Longbaai en de Cat Ba-archipel vormen een karstlandschap in zee. Erosie heeft het kalksteen gevormd tot steile eilanden, grotten en omsloten wateren.'),
('NZL',551,'Te Wahipounamu – South West New Zealand','wildlife',
 'The kea, an alpine parrot, lives in its Te Wahipounamu wilderness.',
 'De kea, een bergpapegaai, leeft in de wildernis van Te Wahipounamu.',
 'Glaciers carved the fjords of its Te Wahipounamu landscape.',
 'Gletsjers sleten de fjorden uit in het landschap van Te Wahipounamu.',
 'Te Wahipounamu spans mountains, glaciers, fjords and ancient forests in the southwest of the South Island. Its wildlife includes the kea and the flightless takahē.',
 'Te Wahipounamu omvat bergen, gletsjers, fjorden en oude bossen in het zuidwesten van het Zuidereiland. Hier leven onder meer de kea en de niet-vliegende takahē.'),
('OMN',1010,'Land of Frankincense','heritage',
 'Frankincense trees in Wadi Dawkah supplied an ancient incense trade.',
 'Wierookbomen in Wadi Dawkah leverden hars voor een eeuwenoude wierookhandel.',
 'Its Shisr oasis and ports of Khor Rori and Al-Baleed served the frankincense trade.',
 'De oase Shisr en de havens Khor Rori en Al-Baleed dienden de wierookhandel.',
 'The Land of Frankincense links groves of incense-producing trees with a caravan oasis and coastal ports. These places record a trade that flourished for centuries.',
 'Het Land van de Wierook verbindt wierookbomen met een karavaanoase en kusthavens. Deze plaatsen herinneren aan een handel die eeuwenlang bloeide.'),
('IRN',1505,'Lut Desert','landscapes',
 'Strong winds carved long, grooved ridges called yardangs in its Lut Desert.',
 'Sterke wind sleet langgerekte ruggen, yardangs genoemd, in de Lutwoestijn.',
 'Its Lut Desert contains wind-sculpted rock ridges and vast dune fields.',
 'De Lutwoestijn bevat door wind gevormde rotsruggen en uitgestrekte duinen.',
 'The Lut Desert is a striking example of erosion and deposition by wind. Its yardangs are long ridges sculpted as wind wears away the softer material around them.',
 'De Lutwoestijn toont hoe wind materiaal wegslijt en afzet. De yardangs zijn langgerekte ruggen die ontstaan doordat zachter materiaal eromheen wordt weggeblazen.'),
('CHL',715,'Rapa Nui National Park','heritage',
 'The monumental moai statues stand on its remote island of Rapa Nui.',
 'De monumentale moaibeelden staan op het afgelegen eiland Rapa Nui.',
 'Polynesian settlers created giant stone figures on its Easter Island.',
 'Polynesische kolonisten maakten reusachtige stenen beelden op Paaseiland.',
 'Rapa Nui, also called Easter Island, is home to the moai. Polynesian communities developed a distinctive monumental tradition on this isolated Pacific island.',
 'Rapa Nui, ook Paaseiland genoemd, is de thuisbasis van de moai. Polynesische gemeenschappen ontwikkelden op dit afgelegen eiland een eigen monumentale traditie.'),
('PER',700,'Lines and Geoglyphs of Nasca and Palpa','heritage',
 'Giant drawings of animals and geometric shapes cover the desert at Nasca.',
 'Reusachtige tekeningen van dieren en geometrische vormen bedekken de woestijn bij Nasca.',
 'Its Nasca and Palpa geoglyphs were created between roughly 500 BC and AD 500.',
 'De geogliefen van Nasca en Palpa ontstonden tussen ongeveer 500 v.Chr. en 500 n.Chr.',
 'The Nasca and Palpa geoglyphs form a vast collection of lines and figures on the arid coastal plain. They depict animals, plants and geometric forms.',
 'De geogliefen van Nasca en Palpa vormen een enorme verzameling lijnen en figuren op een droge kustvlakte. Ze stellen dieren, planten en geometrische vormen voor.'),
('MEX',1290,'Monarch Butterfly Biosphere Reserve','wildlife',
 'Millions of monarch butterflies turn its mountain forests orange each autumn.',
 'Miljoenen monarchvlinders kleuren de bergbossen er elke herfst oranje.',
 'Monarch butterflies spend winter in its central mountain forests before migrating north.',
 'Monarchvlinders overwinteren in de centrale bergbossen voordat ze noordwaarts trekken.',
 'Monarch butterflies gather in dense colonies in the mountain forests of central Mexico. These wintering sites are part of a migration across North America.',
 'Monarchvlinders verzamelen zich in dichte kolonies in de bergbossen van centraal Mexico. Deze overwinteringsplaatsen maken deel uit van hun trek door Noord-Amerika.'),
('JPN',662,'Yakushima','wildlife',
 'Ancient sugi trees grow in the forests of its island Yakushima.',
 'In de bossen van het eiland Yakushima groeien eeuwenoude sugibomen.',
 'Its mountainous Yaku Island preserves warm-temperate forest and ancient cedars.',
 'Het bergachtige eiland Yaku bewaart warm-gematigd bos en oude ceders.',
 'Yakushima is a mountainous island with a wide range of vegetation. Its forests include ancient sugi trees, often called Japanese cedars.',
 'Yakushima is een bergachtig eiland met uiteenlopende begroeiing. De bossen bevatten oude sugibomen, die vaak Japanse ceders worden genoemd.'),
('USA',28,'Yellowstone National Park','water',
 'Geysers and hot springs fill its Yellowstone National Park.',
 'Geisers en warmwaterbronnen vullen Yellowstone National Park.',
 'Its Yellowstone protected landscape became a national park in 1872.',
 'Het beschermde landschap Yellowstone werd in 1872 een nationaal park.',
 'Yellowstone became a national park in 1872. Beneath its forests and lakes, volcanic heat powers an extraordinary concentration of hot springs and geysers.',
 'Yellowstone werd in 1872 een nationaal park. Onder de bossen en meren voedt vulkanische warmte een uitzonderlijke verzameling warmwaterbronnen en geisers.'),
('CAN',304,'Canadian Rocky Mountain Parks','fossils',
 'The Burgess Shale preserves fossils of soft-bodied sea creatures in its Rocky Mountains.',
 'De Burgess Shale bewaart fossielen van zachte zeedieren in de Rocky Mountains.',
 'Its mountain parks include Banff, Jasper, Kootenay and Yoho.',
 'De bergparken omvatten onder meer Banff, Jasper, Kootenay en Yoho.',
 'The Rocky Mountain Parks protect glaciers, peaks, lakes and forests. The Burgess Shale is especially valuable because it preserves details of ancient soft-bodied marine animals.',
 'De Rocky Mountain Parks beschermen gletsjers, bergtoppen, meren en bossen. De Burgess Shale is bijzonder doordat details van zachte, oude zeedieren bewaard zijn gebleven.'),
('ETH',18,'Rock-Hewn Churches, Lalibela','heritage',
 'Eleven medieval churches at Lalibela were cut directly into rock.',
 'Elf middeleeuwse kerken bij Lalibela zijn rechtstreeks uit de rotsen gehouwen.',
 'Its mountain town of Lalibela is known for monolithic churches from the 13th century.',
 'De bergplaats Lalibela staat bekend om monolithische kerken uit de 13e eeuw.',
 'Lalibela’s churches were carved from rock rather than assembled from stone blocks. This medieval religious centre remains a place of pilgrimage.',
 'De kerken van Lalibela werden uit rotsen gehouwen in plaats van opgebouwd uit steenblokken. Dit middeleeuwse religieuze centrum is nog steeds een bedevaartsoord.'),
('SVN',390,'Škocjan Caves','caves',
 'Underground waterfalls run through its enormous Škocjan cave system.',
 'Ondergrondse watervallen stromen door het enorme grottenstelsel van Škocjan.',
 'Its Škocjan caves form a vast limestone landscape beneath the Kras region.',
 'De grotten van Škocjan vormen een uitgestrekt kalksteenlandschap onder de regio Kras.',
 'The Škocjan system combines caves, collapsed sinkholes and underground waters. It is a major example of karst, a landscape formed when water dissolves soluble rock.',
 'Het stelsel van Škocjan combineert grotten, ingestorte zinkgaten en ondergronds water. Het is een belangrijk voorbeeld van karst: een landschap gevormd doordat water gesteente oplost.'),
('ZWE',364,'Great Zimbabwe National Monument','heritage',
 'A medieval Shona trading city left monumental stone ruins in its highlands.',
 'Een middeleeuwse Shona-handelsstad liet monumentale stenen ruïnes achter in het hoogland.',
 'Its major medieval Shona city flourished as a trading centre from the 11th to 15th centuries.',
 'Een grote middeleeuwse Shona-stad bloeide er van de 11e tot de 15e eeuw als handelscentrum.',
 'Great Zimbabwe was an important Shona trading centre during the Middle Ages. Its monumental ruins preserve evidence of a sophisticated urban society.',
 'Groot-Zimbabwe was in de middeleeuwen een belangrijk Shona-handelscentrum. De monumentale ruïnes getuigen van een ontwikkelde stedelijke samenleving.'),
('PHL',722,'Rice Terraces of the Philippine Cordilleras','heritage',
 'Ifugao communities shaped mountain slopes into rice terraces over many generations.',
 'Ifugao-gemeenschappen vormden berghellingen generaties lang om tot rijstterrassen.',
 'Its Ifugao rice fields follow the contours of steep mountain slopes.',
 'De rijstvelden van de Ifugao volgen de contouren van steile berghellingen.',
 'The Cordillera rice terraces reflect knowledge passed down through generations of Ifugao farmers. Water management and careful cultivation sustain this mountain landscape.',
 'De rijstterrassen van de Cordillera weerspiegelen kennis die generaties Ifugao-boeren doorgaven. Waterbeheer en zorgvuldige landbouw houden dit berglandschap in stand.'),
('FRA',80,'Mont-Saint-Michel and its Bay','heritage',
 'A Gothic abbey crowns its tidal islet of Mont-Saint-Michel.',
 'Een gotische abdij bekroont het getijdeneiland Mont-Saint-Michel.',
 'Powerful tides surround the rock of its Mont-Saint-Michel abbey.',
 'Krachtige getijden omringen de rots waarop de abdij Mont-Saint-Michel staat.',
 'Mont-Saint-Michel stands on a rocky islet between Normandy and Brittany. Its Benedictine abbey rises above a small village in a bay shaped by powerful tides.',
 'Mont-Saint-Michel staat op een rotseiland tussen Normandië en Bretagne. De benedictijnenabdij torent boven een dorp uit in een baai met krachtige getijden.'),
('BRA',1611,'Lençóis Maranhenses National Park','water',
 'Rain fills hollows between white dunes with lagoons in Lençóis Maranhenses.',
 'Regen vult kuilen tussen witte duinen met lagunes in Lençóis Maranhenses.',
 'Its Lençóis Maranhenses landscape alternates between sand dunes and seasonal lagoons.',
 'Het landschap van Lençóis Maranhenses wisselt zandduinen af met seizoenslagunes.',
 'Lençóis Maranhenses lies on the Atlantic coast. During the rainy season, fresh water gathers between the dunes, creating a shifting mosaic of sand and lagoons.',
 'Lençóis Maranhenses ligt aan de Atlantische kust. Tijdens het regenseizoen verzamelt zoet water zich tussen de duinen en ontstaat een veranderend mozaïek van zand en lagunes.'),
('DEU',720,'Messel Pit Fossil Site','fossils',
 'Some mammal fossils in its Messel Pit still preserve stomach contents.',
 'Sommige zoogdierfossielen uit de Messelgroeve bewaren zelfs de maaginhoud.',
 'Its Messel Pit provides a remarkably detailed record of Eocene mammals.',
 'De Messelgroeve geeft een uitzonderlijk gedetailleerd beeld van zoogdieren uit het Eoceen.',
 'Messel Pit is famous for exceptionally preserved fossils from the Eocene. Some specimens retain fine details of bodies and even the remains of their last meals.',
 'De Messelgroeve staat bekend om uitzonderlijk goed bewaarde fossielen uit het Eoceen. Sommige exemplaren bevatten fijne lichaamsdetails en zelfs resten van hun laatste maaltijd.'),
('IND',243,'Ellora Caves','heritage',
 'Buddhist, Hindu and Jain monuments share the rock-cut site of Ellora.',
 'Boeddhistische, hindoeïstische en jaïnistische monumenten delen de rotslocatie Ellora.',
 'Its Ellora complex contains 34 monasteries and temples cut into basalt cliffs.',
 'Het complex van Ellora bevat 34 kloosters en tempels uitgehouwen in basaltkliffen.',
 'The Ellora monuments were created between about AD 600 and 1000. Three religious traditions are represented side by side in the rock-cut complex.',
 'De monumenten van Ellora ontstonden tussen ongeveer 600 en 1000 n.Chr. Drie religieuze tradities zijn naast elkaar vertegenwoordigd in het uitgehouwen complex.'),
('CHN',1540,'Qinghai Hoh Xil','wildlife',
 'Antelope migrate across the high plateau of its Hoh Xil reserve.',
 'Antilopen trekken over de hoogvlakte van het reservaat Hoh Xil.',
 'Its Hoh Xil wilderness protects a complete migration route for Tibetan antelope.',
 'De wildernis van Hoh Xil beschermt een volledige trekroute van Tibetaanse antilopen.',
 'Hoh Xil protects a vast high-altitude landscape and the migration routes of Tibetan antelope. Plants and animals here are adapted to a cold, oxygen-poor environment.',
 'Hoh Xil beschermt een uitgestrekte hoogvlakte en trekroutes van Tibetaanse antilopen. Planten en dieren zijn er aangepast aan een koude, zuurstofarme omgeving.'),
('ARM',1011,'Cathedral and Churches of Echmiatsin and the Archaeological Site of Zvartnots','heritage',
 'Its churches at Echmiatsin helped shape a distinctive style of domed architecture.',
 'De kerken van Echmiatsin hielpen een eigen stijl van koepelarchitectuur te vormen.',
 'Echmiatsin and the ruins of Zvartnots preserve its early church-building traditions.',
 'Echmiatsin en de ruïnes van Zvartnots bewaren vroege tradities van kerkbouw.',
 'Echmiatsin and Zvartnots illustrate the development of a distinctive church type, combining a central dome with a cross-shaped hall. This architecture influenced the wider region.',
 'Echmiatsin en Zvartnots tonen de ontwikkeling van een kerktype met een centrale koepel en een kruisvormige hal. Deze architectuur beïnvloedde de omliggende regio.'),
('NER',573,'Aïr and Ténéré Natural Reserves','landscapes',
 'Its volcanic Aïr Mountains form an ecological island in the Ténéré desert.',
 'Het vulkanische Aïrgebergte vormt een ecologisch eiland in de Ténéréwoestijn.',
 'Sahel wildlife survives around its Aïr massif, surrounded by the Sahara.',
 'Rond het Aïrmassief overleven Saheldieren, omringd door de Sahara.',
 'The Aïr massif rises within the Ténéré desert. The mountains preserve habitats with Sahelian characteristics amid a much drier Saharan landscape.',
 'Het Aïrmassief rijst op in de Ténéréwoestijn. De bergen bewaren leefgebieden met Sahelkenmerken midden in een veel droger Saharalandschap.'),
('KOR',737,'Haeinsa Temple Janggyeong Panjeon, the Depositories for the Tripitaka Koreana Woodblocks','heritage',
 'Haeinsa Temple keeps Buddhist texts carved onto around 80,000 wooden blocks.',
 'De Haeinsatempel bewaart boeddhistische teksten op ongeveer 80.000 houten blokken.',
 'Its Haeinsa depositories were designed to preserve a medieval woodblock collection.',
 'De bewaarplaatsen van Haeinsa zijn ontworpen om middeleeuwse houtblokken te beschermen.',
 'The Tripitaka Koreana was carved in the thirteenth century. Purpose-built depositories at Haeinsa have helped preserve this enormous collection of wooden printing blocks.',
 'De Tripitaka Koreana werd in de dertiende eeuw uitgehouwen. Speciaal ontworpen bewaarplaatsen in Haeinsa hielpen deze enorme verzameling houten drukblokken te bewaren.'),
('ESP',316,'Burgos Cathedral','heritage',
 'Its Gothic cathedral at Burgos was begun in the 13th century and took centuries to complete.',
 'De gotische kathedraal van Burgos werd in de 13e eeuw begonnen en eeuwenlang uitgebreid.',
 'Burgos Cathedral brings together several centuries of Gothic architecture here.',
 'De kathedraal van Burgos verenigt hier verschillende eeuwen gotische architectuur.',
 'Construction of Burgos Cathedral began in the thirteenth century. Later additions in the fifteenth and sixteenth centuries made it a record of changing Gothic styles.',
 'De bouw van de kathedraal van Burgos begon in de dertiende eeuw. Toevoegingen in de vijftiende en zestiende eeuw laten veranderende gotische stijlen zien.'),
]

catalog = {
 'id':'roviko-mosaic-heritage-v1',
 'source':'UNESCO World Heritage Centre',
 'license':'CC BY-SA 3.0 IGO',
 'license_url':'https://creativecommons.org/licenses/by-sa/3.0/igo/',
 'license_metadata_url':'https://whc.unesco.org/en/licenses/6',
 'imported_at':'2026-09-21',
 'modifications':'Original short English paraphrases and Dutch translations of the cited property descriptions; two clue variants and a learning explanation per property. No photos, emblems or third-party contributions are included.',
 'attribution':'Adapted from UNESCO World Heritage Centre, cited property descriptions, CC BY-SA 3.0 IGO. Adaptations by Roviko. No UNESCO endorsement is implied.',
 'facts':[]
}
for country, source_id, title, category, en1, nl1, en2, nl2, explanation_en, explanation_nl in rows:
 catalog['facts'].append({
  'id':f'heritage-{source_id}', 'countryId':country, 'category':category,
  'clues':[{'en':en1,'nl':nl1},{'en':en2,'nl':nl2}],
  'explanation':{'en':explanation_en,'nl':explanation_nl},
  'source':{'title':title,'url':f'https://whc.unesco.org/en/list/{source_id}/'},
  'checked_at':'2026-09-21'
 })
content=json.dumps(catalog, ensure_ascii=False, indent=2)+'\n'
for path in ['lib/data/mosaic-facts.json','public/data/mosaic-facts.json']:
 Path(path).write_text(content)
print(f"Exported {len(rows)} sourced properties / {sum(len(f['clues']) for f in catalog['facts'])} bilingual clues.")
