import { localized } from '../../i18n/content';
export type Localized = { en: string; nl: string; es?: string };
/** `retired` (1.25): no longer chosen for new games (the daily topic, the practice list, Rank Radar boards), but kept so older games still show. */
export type Topic = { id: string; emoji: string; label: Localized; prompt: Localized; unit: string; explanation: Localized; retired?: boolean };
const text = localized;
export const TOPICS: Topic[] = [
  { id: 'population', emoji: '👥', label: text('Population', 'Bevolking'), prompt: text('Which country has more people?', 'Welk land heeft meer inwoners?'), unit: 'number', explanation: text('Total resident population, including all ages.', 'De totale bevolking, van alle leeftijden.') },
  { id: 'forest', emoji: '🌲', label: text('Forest cover', 'Bosbedekking'), prompt: text('Which country has a larger share of forest?', 'Welk land is voor een groter deel bedekt met bos?'), unit: 'percent', explanation: text('Forest as a percentage of land area, not the total size of its forests.', 'Bos als percentage van het landoppervlak, niet de totale bosoppervlakte.') , retired: true },
  { id: 'area', emoji: '🗺️', label: text('Country size', 'Landoppervlakte'), prompt: text('Which country covers more area?', 'Welk land heeft een grotere oppervlakte?'), unit: 'area', explanation: text('Total area from the country catalog. Territorial conventions follow the source.', 'Totale oppervlakte uit de landencatalogus. De territoriale indeling volgt de bron.') },
  { id: 'life', emoji: '🎂', label: text('Life expectancy', 'Levensverwachting'), prompt: text('Where is life expectancy at birth higher?', 'Waar is de levensverwachting bij geboorte hoger?'), unit: 'years', explanation: text('Expected years of life at birth, based on mortality rates in the reference year.', 'Verwachte levensduur bij geboorte, op basis van sterftecijfers in het referentiejaar.') },
  { id: 'urban', emoji: '🏙️', label: text('City living', 'Stadsleven'), prompt: text('Where does a larger share of people live in cities?', 'Waar woont een groter deel van de bevolking in steden?'), unit: 'percent', explanation: text('Urban population as a share of the total. Urban definitions vary by country.', 'Stedelijke bevolking als deel van het totaal. De definitie van stedelijk verschilt per land.') , retired: true },
  { id: 'income', emoji: '💼', label: text('GDP per person', 'Bbp per inwoner'), prompt: text('Which country has a higher GDP per person?', 'Welk land heeft een hoger bbp per inwoner?'), unit: 'dollars', explanation: text('GDP divided by population, in current US dollars. This is not a measure of personal salary.', 'Bbp gedeeld door het inwonertal, in lopende Amerikaanse dollars. Dit is geen persoonlijk salaris.') },
  { id: 'borders', emoji: '🤝', label: text('Land neighbours', 'Buurlanden'), prompt: text('Which country has more land neighbours?', 'Welk land heeft meer buurlanden over land?'), unit: 'borders', explanation: text('Land neighbours in the source catalog. Sea boundaries do not count.', 'Buurlanden over land volgens de bron. Zeegrenzen tellen niet mee.') },
  { id: 'internet', emoji: '📶', label: text('Internet use', 'Internetgebruik'), prompt: text('Where does a larger share of people use the internet?', 'Waar gebruikt een groter deel van de bevolking internet?'), unit: 'percent', explanation: text('People who used the internet in the last three months, as a share of the population.', 'Mensen die in de afgelopen drie maanden internet gebruikten, als deel van de bevolking.') , retired: true },
  { id: 'births', emoji: '🍼', label: text('Births per woman', 'Kinderen per vrouw'), prompt: text('Where is the fertility rate higher?', 'Waar is het vruchtbaarheidscijfer hoger?'), unit: 'births', explanation: text('Expected births per woman if the reference year’s age-specific fertility rates remained constant.', 'Verwacht aantal kinderen per vrouw als de leeftijdsspecifieke cijfers van het referentiejaar gelijk zouden blijven.') , retired: true },
  { id: 'farmland', emoji: '🌾', label: text('Agricultural land', 'Landbouwgrond'), prompt: text('Which country has a larger share of agricultural land?', 'Welk land bestaat voor een groter deel uit landbouwgrond?'), unit: 'percent', explanation: text('Arable land, permanent crops and permanent pasture as a percentage of land area.', 'Akkerland, meerjarige gewassen en permanent grasland als percentage van het landoppervlak.') , retired: true },
  { id: 'economy', emoji: '🏦', label: text('Total economy', 'Totale economie'), prompt: text('Which country has a larger total GDP?', 'Welk land heeft een groter totaal bbp?'), unit: 'dollars', explanation: text('Annual gross domestic product in current US dollars; exchange rates affect comparisons.', 'Jaarlijks bruto binnenlands product in lopende Amerikaanse dollars; wisselkoersen beïnvloeden de vergelijking.') },
  { id: 'equator', emoji: '🌐', label: text('From the equator', 'Vanaf de evenaar'), prompt: text('Which country’s reference point is farther from the equator?', 'Van welk land ligt het referentiepunt verder van de evenaar?'), unit: 'km', explanation: text('Distance from the equator to the catalog’s representative point, not the closest border.', 'Afstand van de evenaar tot het representatieve punt uit de catalogus, niet tot de dichtstbijzijnde grens.') },
  { id: 'exports', emoji: '🚢', label: text('Exports', 'Export'), prompt: text('Where are exports a larger share of GDP?', 'Waar is export een groter deel van het bbp?'), unit: 'percent', explanation: text('Exports of goods and services relative to GDP. This can exceed 100% in trading economies.', 'Uitvoer van goederen en diensten ten opzichte van het bbp. Dit kan boven 100% liggen in handelseconomieën.') , retired: true },
  { id: 'north', emoji: '🧭', label: text('Further north', 'Noordelijker'), prompt: text('Which country’s reference point is farther north?', 'Van welk land ligt het referentiepunt noordelijker?'), unit: 'latitude', explanation: text('Latitude of the catalog’s representative point, not the northernmost border.', 'Breedtegraad van het representatieve punt uit de catalogus, niet van de noordelijkste grens.') },
  // 1.25: livelier subjects from the archived Factbook (see fun-metrics.ts).
  { id: 'highest', emoji: '🏔️', label: text('Highest point', 'Hoogste punt', 'Punto más alto'), prompt: text('Which country has the higher highest point?', 'Welk land heeft het hoogste hoogste punt?', '¿Qué país tiene el punto más alto más elevado?'), unit: 'm', explanation: text('Height above sea level of the highest point, from the archived Factbook.', 'Hoogte boven zeeniveau van het hoogste punt, uit het Factbook-archief.', 'Altura sobre el nivel del mar del punto más alto, del archivo del Factbook.') },
  { id: 'coastline', emoji: '🌊', label: text('Coastline', 'Kustlijn', 'Costa'), prompt: text('Which country has the longer coastline?', 'Welk land heeft de langste kustlijn?', '¿Qué país tiene más kilómetros de costa?'), unit: 'km', explanation: text('Coastline length in the archived Factbook, islands included. Landlocked countries have 0 km.', 'Lengte van de kust in het Factbook-archief, eilanden meegeteld. Landen zonder zee hebben 0 km.', 'Longitud de la costa en el archivo del Factbook, islas incluidas. Los países sin mar tienen 0 km.') },
  { id: 'military', emoji: '🪖', label: text('Military budget', 'Defensiebudget', 'Gasto militar'), prompt: text('Which country spends more on its armed forces?', 'Welk land geeft meer uit aan defensie?', '¿Qué país gasta más en sus fuerzas armadas?'), unit: 'dollars', explanation: text('An estimate: the latest military spending as a share of GDP (Factbook archive) times GDP (World Bank).', 'Een schatting: de laatste defensie-uitgaven als deel van het bbp (Factbook-archief) maal het bbp (Wereldbank).', 'Una estimación: el último gasto militar como parte del PIB (archivo del Factbook) por el PIB (Banco Mundial).') },
  { id: 'alcohol', emoji: '🍺', label: text('Alcohol', 'Alcohol', 'Alcohol'), prompt: text('Where do people drink more alcohol?', 'Waar drinken mensen meer alcohol?', '¿Dónde se bebe más alcohol?'), unit: 'litres', explanation: text('Litres of pure alcohol per person aged 15 or older per year (2019 estimate, Factbook archive).', 'Liters pure alcohol per persoon van 15 jaar of ouder per jaar (schatting 2019, Factbook-archief).', 'Litros de alcohol puro por persona de 15 años o más al año (estimación de 2019, archivo del Factbook).') },
  { id: 'airports', emoji: '✈️', label: text('Airports', 'Vliegvelden', 'Aeropuertos'), prompt: text('Which country has more airports?', 'Welk land heeft meer vliegvelden?', '¿Qué país tiene más aeropuertos?'), unit: 'number', explanation: text('Airports and airfields of every size, including small grass strips (Factbook archive).', 'Vliegvelden van elke grootte, ook kleine graspistes (Factbook-archief).', 'Aeropuertos y aeródromos de todos los tamaños, incluidas pequeñas pistas de hierba (archivo del Factbook).') },
  { id: 'railways', emoji: '🚂', label: text('Railways', 'Spoorwegen', 'Ferrocarriles'), prompt: text('Which country has more railway track?', 'Welk land heeft meer kilometer spoor?', '¿Qué país tiene más kilómetros de vía férrea?'), unit: 'km', explanation: text('Total length of the railway network (Factbook archive). Countries without trains are left out.', 'Totale lengte van het spoornet (Factbook-archief). Landen zonder treinen doen niet mee.', 'Longitud total de la red ferroviaria (archivo del Factbook). Los países sin trenes no participan.') },
];
/** The subjects new games choose from. */
export const ACTIVE_TOPICS = TOPICS.filter(t => !t.retired);
export function formatMetric(value: number, unit: string, locale: 'en' | 'nl' | 'es') {
  if (unit === 'dollars' && value >= 1e9) return '$' + new Intl.NumberFormat(locale === 'es' ? 'es-ES' : locale === 'nl' ? 'nl-NL' : 'en-GB', { notation: 'compact', maximumFractionDigits: 1 }).format(value);
  const number = new Intl.NumberFormat(locale === 'es' ? 'es-ES' : locale === 'nl' ? 'nl-NL' : 'en-GB', { maximumFractionDigits: ['percent', 'years', 'births', 'latitude', 'litres'].includes(unit) ? 1 : 0 });
  const n = number.format(unit === 'latitude' ? Math.abs(value) : value);
  return unit === 'percent' ? n + '%' : unit === 'area' ? n + ' km²' : unit === 'km' ? n + ' km' : unit === 'dollars' ? '$' + n : unit === 'years' ? n + (locale === 'es' ? ' años' : locale === 'nl' ? ' jaar' : ' years') : unit === 'litres' ? n + (locale === 'es' ? ' litros' : locale === 'nl' ? ' liter' : ' litres') : unit === 'births' ? n + (locale === 'es' ? ' por mujer' : locale === 'nl' ? ' per vrouw' : ' per woman') : unit === 'latitude' ? n + '° ' + (value < 0 ? (locale === 'nl' ? 'Z' : 'S') : 'N') : n;
}
