export type Localized = { en: string; nl: string };
export type Topic = { id: string; emoji: string; label: Localized; prompt: Localized; unit: string; explanation: Localized };
const text = (en: string, nl: string): Localized => ({ en, nl });
export const TOPICS: Topic[] = [
  { id: 'population', emoji: '👥', label: text('Population', 'Bevolking'), prompt: text('Which country has more people?', 'Welk land heeft meer inwoners?'), unit: 'number', explanation: text('Total resident population, including all ages.', 'De totale bevolking, van alle leeftijden.') },
  { id: 'forest', emoji: '🌲', label: text('Forest cover', 'Bosbedekking'), prompt: text('Which country has a larger share of forest?', 'Welk land is voor een groter deel bedekt met bos?'), unit: 'percent', explanation: text('Forest as a percentage of land area, not the total size of its forests.', 'Bos als percentage van het landoppervlak, niet de totale bosoppervlakte.') },
  { id: 'area', emoji: '🗺️', label: text('Country size', 'Landoppervlakte'), prompt: text('Which country covers more area?', 'Welk land heeft een grotere oppervlakte?'), unit: 'area', explanation: text('Total area from the country catalog. Territorial conventions follow the source.', 'Totale oppervlakte uit de landencatalogus. De territoriale indeling volgt de bron.') },
  { id: 'life', emoji: '🎂', label: text('Life expectancy', 'Levensverwachting'), prompt: text('Where is life expectancy at birth higher?', 'Waar is de levensverwachting bij geboorte hoger?'), unit: 'years', explanation: text('Expected years of life at birth, based on mortality rates in the reference year.', 'Verwachte levensduur bij geboorte, op basis van sterftecijfers in het referentiejaar.') },
  { id: 'urban', emoji: '🏙️', label: text('City living', 'Stadsleven'), prompt: text('Where does a larger share of people live in cities?', 'Waar woont een groter deel van de bevolking in steden?'), unit: 'percent', explanation: text('Urban population as a share of the total. Urban definitions vary by country.', 'Stedelijke bevolking als deel van het totaal. De definitie van stedelijk verschilt per land.') },
  { id: 'income', emoji: '💼', label: text('GDP per person', 'Bbp per inwoner'), prompt: text('Which country has a higher GDP per person?', 'Welk land heeft een hoger bbp per inwoner?'), unit: 'dollars', explanation: text('GDP divided by population, in current US dollars. This is not a measure of personal salary.', 'Bbp gedeeld door het inwonertal, in lopende Amerikaanse dollars. Dit is geen persoonlijk salaris.') },
  { id: 'borders', emoji: '🤝', label: text('Land neighbours', 'Buurlanden'), prompt: text('Which country has more land neighbours?', 'Welk land heeft meer buurlanden over land?'), unit: 'borders', explanation: text('Land neighbours in the source catalog. Sea boundaries do not count.', 'Buurlanden over land volgens de bron. Zeegrenzen tellen niet mee.') },
  { id: 'internet', emoji: '📶', label: text('Internet use', 'Internetgebruik'), prompt: text('Where does a larger share of people use the internet?', 'Waar gebruikt een groter deel van de bevolking internet?'), unit: 'percent', explanation: text('People who used the internet in the last three months, as a share of the population.', 'Mensen die in de afgelopen drie maanden internet gebruikten, als deel van de bevolking.') },
  { id: 'births', emoji: '🍼', label: text('Births per woman', 'Kinderen per vrouw'), prompt: text('Where is the fertility rate higher?', 'Waar is het vruchtbaarheidscijfer hoger?'), unit: 'births', explanation: text('Expected births per woman if the reference year’s age-specific fertility rates remained constant.', 'Verwacht aantal kinderen per vrouw als de leeftijdsspecifieke cijfers van het referentiejaar gelijk zouden blijven.') },
  { id: 'farmland', emoji: '🌾', label: text('Agricultural land', 'Landbouwgrond'), prompt: text('Which country has a larger share of agricultural land?', 'Welk land bestaat voor een groter deel uit landbouwgrond?'), unit: 'percent', explanation: text('Arable land, permanent crops and permanent pasture as a percentage of land area.', 'Akkerland, meerjarige gewassen en permanent grasland als percentage van het landoppervlak.') },
  { id: 'economy', emoji: '🏦', label: text('Total economy', 'Totale economie'), prompt: text('Which country has a larger total GDP?', 'Welk land heeft een groter totaal bbp?'), unit: 'dollars', explanation: text('Annual gross domestic product in current US dollars; exchange rates affect comparisons.', 'Jaarlijks bruto binnenlands product in lopende Amerikaanse dollars; wisselkoersen beïnvloeden de vergelijking.') },
  { id: 'equator', emoji: '🌐', label: text('From the equator', 'Vanaf de evenaar'), prompt: text('Which country’s reference point is farther from the equator?', 'Van welk land ligt het referentiepunt verder van de evenaar?'), unit: 'km', explanation: text('Distance from the equator to the catalog’s representative point, not the closest border.', 'Afstand van de evenaar tot het representatieve punt uit de catalogus, niet tot de dichtstbijzijnde grens.') },
  { id: 'exports', emoji: '🚢', label: text('Exports', 'Export'), prompt: text('Where are exports a larger share of GDP?', 'Waar is export een groter deel van het bbp?'), unit: 'percent', explanation: text('Exports of goods and services relative to GDP. This can exceed 100% in trading economies.', 'Uitvoer van goederen en diensten ten opzichte van het bbp. Dit kan boven 100% liggen in handelseconomieën.') },
  { id: 'north', emoji: '🧭', label: text('Further north', 'Noordelijker'), prompt: text('Which country’s reference point is farther north?', 'Van welk land ligt het referentiepunt noordelijker?'), unit: 'latitude', explanation: text('Latitude of the catalog’s representative point, not the northernmost border.', 'Breedtegraad van het representatieve punt uit de catalogus, niet van de noordelijkste grens.') },
];
export function formatMetric(value: number, unit: string, locale: 'en' | 'nl') {
  if (unit === 'dollars' && value >= 1e9) return '$' + new Intl.NumberFormat(locale === 'nl' ? 'nl-NL' : 'en-GB', { notation: 'compact', maximumFractionDigits: 1 }).format(value);
  const number = new Intl.NumberFormat(locale === 'nl' ? 'nl-NL' : 'en-GB', { maximumFractionDigits: ['percent', 'years', 'births', 'latitude'].includes(unit) ? 1 : 0 });
  const n = number.format(unit === 'latitude' ? Math.abs(value) : value);
  return unit === 'percent' ? n + '%' : unit === 'area' ? n + ' km²' : unit === 'km' ? n + ' km' : unit === 'dollars' ? '$' + n : unit === 'years' ? n + (locale === 'nl' ? ' jaar' : ' years') : unit === 'births' ? n + (locale === 'nl' ? ' per vrouw' : ' per woman') : unit === 'latitude' ? n + '° ' + (value < 0 ? (locale === 'nl' ? 'Z' : 'S') : 'N') : n;
}
