import { sql } from 'drizzle-orm';
import { sqliteTable, text, integer, real, index, uniqueIndex, primaryKey, check } from 'drizzle-orm/sqlite-core';
export const users = sqliteTable('users', { id: text('id').primaryKey(), email: text('email'), password: text('password'), name: text('name').notNull(), avatar: integer('avatar').notNull().default(0), guest: integer('guest').notNull().default(1), discoverable: integer('discoverable').notNull().default(1), blocked: integer('blocked').notNull().default(0), createdAt: integer('created_at').notNull() }, t => [uniqueIndex('email_unique').on(t.email)]);
export const sessions = sqliteTable('auth_sessions', { token: text('token').primaryKey(), userId: text('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }), expiresAt: integer('expires_at').notNull() }, t => [index('auth_user').on(t.userId)]);
export const games = sqliteTable('game_sessions', { id: text('id').primaryKey(), userId: text('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }), kind: text('kind').notNull(), date: text('date'), state: text('state').notNull(), version: integer('version').notNull().default(0), score: integer('score').notNull().default(0), completed: integer('completed').notNull().default(0), createdAt: integer('created_at').notNull() }, t => [index('games_user_time').on(t.userId, t.createdAt), uniqueIndex('daily_game_unique').on(t.userId, t.date, t.kind)]);
export const results = sqliteTable('game_results', { id: text('id').primaryKey(), userId: text('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }), mode: text('mode').notNull(), score: integer('score').notNull(), xp: integer('xp').notNull(), correct: integer('correct').notNull(), total: integer('total').notNull(), duration: integer('duration').notNull(), bestStreak: integer('best_streak').notNull(), win: integer('win').notNull().default(0), multiplayer: integer('multiplayer').notNull().default(0), risk: integer('risk').notNull().default(0), createdAt: integer('created_at').notNull() }, t => [index('results_leaderboard').on(t.createdAt, t.score), index('results_user').on(t.userId)]);
export const daily = sqliteTable('daily_challenge_results', { userId: text('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }), date: text('date').notNull(), resultId: text('result_id').notNull().references(() => results.id, { onDelete: 'cascade' }), score: integer('score').notNull() }, t => [primaryKey({ columns: [t.userId, t.date] }), index('daily_ranking').on(t.date, t.score)]);
export const rooms = sqliteTable('multiplayer_rooms', { code: text('code').primaryKey(), state: text('state').notNull(), version: integer('version').notNull().default(0), updatedAt: integer('updated_at').notNull(), expiresAt: integer('expires_at').notNull() });
export const answers = sqliteTable('answers', { sessionId: text('session_id').notNull(), round: integer('round').notNull(), userId: text('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }), questionId: text('question_id').notNull(), countryId: text('country_id').notNull().default(''), mode: text('mode').notNull().default(''), answer: text('answer').notNull(), correct: integer('correct').notNull(), points: integer('points').notNull(), responseTime: integer('response_time').notNull(), risk: integer('risk').notNull().default(0), createdAt: integer('created_at').notNull() }, t => [primaryKey({ columns: [t.sessionId, t.round, t.userId] }), index('answer_user').on(t.userId)]);
export const concepts = sqliteTable('concept_performance', { userId: text('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }), countryId: text('country_id').notNull(), mode: text('mode').notNull(), correct: integer('correct').notNull().default(0), attempts: integer('attempts').notNull().default(0) }, t => [primaryKey({ columns: [t.userId, t.countryId, t.mode] })]);
export const sources = sqliteTable('data_sources', { id: text('id').primaryKey(), name: text('name').notNull(), url: text('url').notNull(), license: text('license').notNull(), importedAt: text('imported_at').notNull(), attribution: text('attribution').notNull() });
export const countries = sqliteTable('countries', { id: text('id').primaryKey(), iso2: text('iso2').notNull(), name: text('name').notNull(), data: text('data').notNull(), sourceId: text('source_id').references(() => sources.id) }, t => [uniqueIndex('iso2_unique').on(t.iso2)]);
export const borders = sqliteTable('country_borders', { countryId: text('country_id').notNull().references(() => countries.id, { onDelete: 'cascade' }), neighborId: text('neighbor_id').notNull().references(() => countries.id, { onDelete: 'cascade' }) }, t => [primaryKey({ columns: [t.countryId, t.neighborId] })]);
export const reports = sqliteTable('question_reports', { id: text('id').primaryKey(), userId: text('user_id').references(() => users.id, { onDelete: 'set null' }), questionId: text('question_id').notNull(), template: text('template').notNull(), category: text('category').notNull(), detail: text('detail'), version: text('app_version').notNull(), status: text('status').notNull().default('open'), createdAt: integer('created_at').notNull() });
export const disabled = sqliteTable('disabled_questions', { questionId: text('question_id').primaryKey(), reason: text('reason').notNull(), createdAt: integer('created_at').notNull() });
export const achievements = sqliteTable('achievements', { id: text('id').primaryKey(), definition: text('definition').notNull() });
export const earned = sqliteTable('user_achievements', { userId: text('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }), achievementId: text('achievement_id').notNull(), earnedAt: integer('earned_at').notNull() }, t => [primaryKey({ columns: [t.userId, t.achievementId] })]);
export const friends = sqliteTable('friend_requests', { id: text('id').primaryKey(), fromId: text('from_id').notNull().references(() => users.id, { onDelete: 'cascade' }), toId: text('to_id').notNull().references(() => users.id, { onDelete: 'cascade' }), status: text('status').notNull().default('pending'), createdAt: integer('created_at').notNull() }, t => [uniqueIndex('friend_pair').on(t.fromId, t.toId)]);
export const ratings = sqliteTable('ratings', { userId: text('user_id').primaryKey().references(() => users.id, { onDelete: 'cascade' }), rating: real('rating').notNull().default(1000), games: integer('games').notNull().default(0) });
export const queue = sqliteTable('matchmaking_queue', { userId: text('user_id').primaryKey().references(() => users.id, { onDelete: 'cascade' }), region: text('region').notNull(), rating: real('rating').notNull(), queuedAt: integer('queued_at').notNull() });
export const limits = sqliteTable('rate_limits', { key: text('key').primaryKey(), count: integer('count').notNull().default(0), resetAt: integer('reset_at').notNull() });
export const events = sqliteTable('analytics_events', { id: text('id').primaryKey(), event: text('event').notNull(), mode: text('mode'), createdAt: integer('created_at').notNull() });
export const dailyContent = sqliteTable('daily_content', { date: text('date').notNull(), kind: text('kind').notNull(), datasetVersion: text('dataset_version').notNull(), content: text('content').notNull(), createdAt: integer('created_at').notNull() }, t => [primaryKey({ columns: [t.date, t.kind] })]);
export const learningReviews = sqliteTable('learning_reviews', { userId: text('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }), key: text('key').notNull(), countryId: text('country_id').notNull(), mode: text('mode').notNull(), topic: text('topic'), content: text('content').notNull(), missed: integer('missed').notNull().default(1), resolved: integer('resolved').notNull().default(0), updatedAt: integer('updated_at').notNull() }, t => [primaryKey({ columns: [t.userId, t.key] }), index('reviews_user_resolved').on(t.userId,t.resolved,t.updatedAt)]);

export const dailyScores = sqliteTable('daily_scores', {
  userId: text('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  date: text('date').notNull(), mode: text('mode').notNull(),
  sessionId: text('session_id').notNull().references(() => games.id, { onDelete: 'cascade' }),
  score: integer('score').notNull(), scoringVersion: integer('scoring_version').notNull().default(1), createdAt: integer('created_at').notNull(),
}, t => [primaryKey({columns:[t.userId,t.date,t.mode]}), uniqueIndex('daily_score_session').on(t.sessionId), index('daily_scores_ranking').on(t.date,t.mode,t.score), check('daily_score_bounds',sql`${t.score} BETWEEN 0 AND 1000`), check('daily_score_modes',sql`${t.mode} IN ('daily','trail','compare','mosaic','rank')`)]);
// 1.15: who is online (a heartbeat while the site is open) and direct room invites between friends.
export const presence = sqliteTable('user_presence', {
  userId: text('user_id').primaryKey().references(() => users.id, { onDelete: 'cascade' }),
  lastSeen: integer('last_seen').notNull(), roomCode: text('room_code'),
}, t => [index('presence_seen').on(t.lastSeen)]);
export const roomInvites = sqliteTable('room_invites', {
  id: text('id').primaryKey(),
  fromId: text('from_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  toId: text('to_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  roomCode: text('room_code').notNull(), status: text('status').notNull().default('pending'), createdAt: integer('created_at').notNull(),
}, t => [index('room_invites_to').on(t.toId, t.status, t.createdAt), uniqueIndex('room_invite_pair').on(t.fromId, t.toId, t.roomCode)]);
