import React from 'react';
/** Spanish policy draft and source credits; source identities and licence links are retained. */
export function SpanishInfo({kind}:{kind:string}) {
 const source=(title:string,copy:string,href:string,label:string)=><section className="source-card"><h2>{title}</h2><p>{copy}</p><a href={href}>{label} ↗</a></section>;
 return <article className="info-page"><a className="text-link" href="/">← Volver</a><h1>{kind==='sources'?'Los buenos juegos empiezan con buenas fuentes.':kind==='privacy'?'Tu privacidad, en palabras claras':'Unas reglas básicas'}</h1>{kind==='sources'?<>
 <p>Las preguntas se generan a partir de datos geográficos abiertos. La colección incluye 193 miembros de la ONU y sus dos Estados observadores. Las traducciones cambian la presentación, no los datos ni las respuestas.</p>
 {source('World countries · 5.1.0','Mohammed Le Doze y colaboradores · ODbL 1.0 · importación: 2026-09-08. Datos de países, nombres localizados, fronteras y siluetas. Contiene información de World countries bajo la Open Database License.','https://github.com/mledoze/countries','Repositorio y atribución')}
 <p><a href="/data/countries.json" download>Descargar países</a> · <a href="/data/boundaries.json" download>Fronteras</a> · <a href="/data/silhouettes.json" download>Siluetas</a> · <a href="/licenses/countries-ODbL.txt">ODbL 1.0</a></p>
 {source('World Development Indicators · 2023','Banco Mundial · CC BY 4.0 · importación: 2026-09-09. Diez indicadores de población, ciudades, esperanza de vida, fecundidad, PIB, bosques, agricultura, exportaciones e internet. El archivo conserva los proveedores por indicador. Se omiten los datos ausentes y solo se redondea su presentación.','https://datacatalog.worldbank.org/search/dataset/0037712/world-development-indicators','Catálogo del Banco Mundial')}
 <p><a href="/data/comparisons.json" download>Descargar indicadores y fuentes</a> · <a href="https://www.worldbank.org/ext/en/legal/terms-conditions/datasets">Condiciones de uso del Banco Mundial</a></p>
 {source('Mosaic · cifras de países','Cada ficha muestra un dato, como altitud, costa, edad mediana o PIB. Los temas cambian cada día UTC. Indicamos los años y las estimaciones; nunca inventamos valores ausentes. La altitud, costa y edad mediana proceden del archivo CC0 factbook.json del CIA World Factbook. Son observaciones archivadas, no mediciones en directo.','/data/country-metrics.json','Datos, fuentes y correcciones')}
 <p>La longitud de costa depende del método de medición. La edad mediana divide la población en dos mitades de igual tamaño; no es la esperanza de vida. Las altitudes con contradicciones conocidas se omiten o se corrigen con una fuente verificable. <a href="/licenses/factbook-CC0.txt">CC0 1.0</a>.</p>
 {source('UNESCO World Heritage Centre','Las pistas de patrimonio son adaptaciones abreviadas y traducidas por Roviko. Se publican bajo CC BY-SA 3.0 IGO. UNESCO no respalda Roviko.','/data/mosaic-facts.json','Pistas y fuentes originales')}
 <p><a href="https://creativecommons.org/licenses/by-sa/3.0/igo/">CC BY-SA 3.0 IGO</a></p>
 {source('Natural Earth · world-atlas 2.0.2','Datos cartográficos de dominio público. World-atlas © Michael Bostock, licencia ISC. Geometría simplificada a escala 1:110 millones; los países muy pequeños pueden no verse. Made with Natural Earth.','https://www.naturalearthdata.com/about/terms-of-use/','Natural Earth')}
 <p><a href="/licenses/world-atlas-ISC.txt">Licencia ISC</a></p>
 {source('flag-icons · 7.5.0','© Panayiotis Lipiridis · MIT. Banderas utilizadas en los juegos.','https://github.com/lipis/flag-icons','flag-icons')}
 <p><a href="/licenses/flags-MIT.txt">Licencia MIT</a></p>
 <h2>Criterios geográficos</h2><p>Un mapa sirve para aprender, no expresa una postura política. Excluimos preguntas sobre capitales disputadas y algunas fronteras sensibles. Pinpoint usa fronteras simplificadas con 25 km de tolerancia. Las partidas anteriores mantienen su regla original. Los aciertos reciben la puntuación completa; los errores reciben puntos decrecientes según la distancia. Las siluetas muestran las principales masas terrestres y pueden omitir islas pequeñas o remotas.</p>
 <h2>Diseño y código</h2><p>El diseño, los textos, el generador de preguntas y el globo de Roviko son originales. Las ilustraciones de los juegos y los sellos se crearon para Roviko. Los iconos son de Lucide (ISC). Las fuentes Nunito, Fredoka, Manrope y Outfit usan SIL Open Font License.</p><p>{['nunito','fredoka','manrope','outfit'].map(font=><React.Fragment key={font}><a href={'/fonts/'+font+'-LICENSE'}>{font} · OFL</a>{' · '}</React.Fragment>)}<a href="/licenses/lucide-ISC.txt">Lucide · ISC</a></p>
 </>:<><p className="policy-note">Política provisional para esta primera versión. Requiere revisión jurídica antes del lanzamiento comercial.</p>{kind==='privacy'?<>
 <h2>Qué guardamos</h2><p>Al jugar como invitado guardamos un identificador de sesión aleatorio, el nombre elegido, los resultados y el progreso. Una cuenta añade tu correo electrónico y un hash de contraseña con sal. Nunca guardamos la contraseña legible.</p>
 <h2>Almacenamiento necesario</h2><p>Una cookie necesaria mantiene tu sesión. El tema, idioma y sonido se guardan en el navegador. No hay rastreadores publicitarios. Puedes activar mediciones opcionales en tu pasaporte: eventos e identificadores seudonimizados, sin nombre, correo, dirección IP ni respuestas. La cookie de preferencia solo indica si están activadas. Los nombres y las puntuaciones aparecen en salas y clasificaciones.</p>
 <h2>Tus decisiones</h2><p>Desde tu pasaporte puedes desactivar solicitudes de amistad, descargar tus datos y eliminar la cuenta. El progreso de invitado está vinculado a la cookie de sesión. Las sesiones caducan a los 30 días y las salas tras 30 minutos sin jugadores activos.</p><a className="btn secondary" href="/profile">Tu pasaporte →</a>
 <h2>Antes del lanzamiento comercial</h2><p>El responsable debe definir el responsable del tratamiento, datos de contacto, plazos de conservación y condiciones aplicables, y solicitar revisión jurídica de este borrador.</p>
 </>:<><h2>Juega limpio</h2><p>Elige un nombre respetuoso. No manipules puntuaciones, automatices envíos a clasificaciones ni interrumpas salas ajenas. El abuso grave puede conllevar el bloqueo de la cuenta.</p><h2>Aprende con mente abierta</h2><p>Los datos geográficos pueden cambiar. Informa de una pregunta si ves un error. Los mapas son simplificados y las fronteras no expresan una postura sobre soberanía.</p><h2>Juega gratis</h2><p>Los juegos actuales son gratuitos. No hay pagos ni ventajas de conocimiento comprables. Las licencias de las fuentes siguen aplicándose a los datos geográficos y recursos abiertos.</p><a href="/sources">Datos y créditos →</a></>}</>}</article>;
}
